### ISSUE TITLE
VerifyXml fails with "No State found. Ensure a class inheriting from VerifyTestProject exists in the test project"

### ISSUE THREAD

**Issue by thostr** [VerifyTests/Verify#1200]
Versions involved:
*  Xunit/2.8.0
* Verify.Xunit/24.1.0
* Verify.Fixie/24.1.0
Framework: net 8
Rider 

Given the following test:

   [Fact, UnitTest]
    public async Task VerifyXml_Problem()
    {
        await VerifyFixie.Verifier.VerifyXml("<problem/>");
    }

Fails with:

System.Exception
No State found. Ensure a class inheriting from VerifyTestProject exists in the test project.
public class TestProject :
    VerifyTestProject;
   at VerifyFixie.ExecutionState.get_Current() in /_/src/Verify.Fixie/Execution/ExecutionState.cs:line 26
   at VerifyFixie.Verifier.BuildVerifier(String sourceFile, VerifySettings settings, Boolean useUniqueDirectory) in /_/src/Verify.Fixie/Verifier.cs:line 14
   at VerifyFixie.Verifier.<>c__DisplayClass5_0.<<Verify>b__0>d.MoveNext() in /_/src/Verify.Fixie/Verifier.cs:line 46
--- End of stack trace from previous location ---
   at TestDIPS.InterHospitalReferral.Domain.StatusMessageImport.ApprecBuilderTests.VerifyXml_Problem() in C:\Users\ths\source\Repos\InterHospitalReferral.Service\src\Test\UnitTests\TestDIPS.InterHospitalReferral.Domain\StatusMessageImport\ApprecBuilderTests.cs:line 24
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 253
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90

Can't find any VerifyTestProject class that I can subclass.

**Comment by thostr** [comment]
Works with await VerifyXunit.Verifier.VerifyXml(apprec);

**Comment by SimonCropp** [comment]
why are you mixing Verify.Xunit and Verify.Fixie?
