### ISSUE TITLE
Could not find a `AssemblyMetadataAttribute` named `XXX.SolutionDirectory`

### ISSUE THREAD

**Issue by michael-wolfenden** [VerifyTests/Verify#1304]
#### Describe the bug

The following test fails during CI when running `dotnet test` against a specific project rather than against the solution

```csharp
public class VerifySpecs
{
    [Fact]
    public Task verify_is_configured_correctly() =>
        VerifyChecks.Run();
}
```

`dotnet test VerifyIssue.Tests/VerifyIssue.Tests.csproj` fails with

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:00.22]     VerifyIssue.Tests.VerifySpecs.verify_is_configured_correctly [FAIL]
  Failed VerifyIssue.Tests.VerifySpecs.verify_is_configured_correctly [4 ms]
  Error Message:
   System.Exception : Could not find a `AssemblyMetadataAttribute` named `Verify.SolutionDirectory` on VerifyIssue.Tests.
  Stack Trace:
     at VerifyTests.AttributeReader.GetValue(Assembly assembly, String key, Boolean isSourcePath) in /_/src/Verify/DerivePaths/AttributeReader.cs:line 111
   at VerifyTests.AttributeReader.GetSolutionDirectory(Assembly assembly) in /_/src/Verify/DerivePaths/AttributeReader.cs:line 48
   at VerifyTests.InnerVerifyChecks.Run(Assembly assembly) in /_/src/Verify/ConventionCheck/InnerVerifyChecks.cs:line 9
   at VerifyXunit.VerifyChecks.Run() in /_/src/Verify.Xunit/VerifyChecks.cs:line 10
   at VerifyIssue.Tests.VerifySpecs.verify_is_configured_correctly() in /home/vsts/work/1/s/VerifyIssue.Tests/VerifySpecs.cs:line 7
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

`dotnet test VerifyIssue.sln` succeeds

#### Minimal Repro

https://github.com/michael-wolfenden/verify-issue

**Comment by SimonCropp** [comment]
this will be fixed in V27

or u can use the current beta 27.0.0-beta.5
