### ISSUE TITLE
System.TypeLoadException : Could not load type Polyfill from assembly Argon

### ISSUE THREAD

**Issue by lkurzyniec** [VerifyTests/Verify#1321]
The newest version `27.0.1` is causing error:
>  System.TypeLoadException : Could not load type 'Polyfill' from assembly 'Argon, Version=1.0.0.0, Culture=neutral, PublicKeyToken=00a55352ff068a54'.

with a stack trace:
```
at Argon.XmlNodeConverter.CanConvert(Type valueType)
   at Argon.JsonSerializer.GetMatchingConverter(IList`1 converters, Type type) in /_/src/Argon/JsonSerializer.cs:line 685
   at Argon.JsonSerializer.GetMatchingConverter(Type type) in /_/src/Argon/JsonSerializer.cs:line 677
   at JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty) in /_/src/Argon/Serialization/JsonSerializerInternalWriter.cs:line 106
   at JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type type) in /_/src/Argon/Serialization/JsonSerializerInternalWriter.cs:line 30
   at Argon.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type type) in /_/src/Argon/JsonSerializer.cs:line 649
   at Argon.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value) in /_/src/Argon/JsonSerializer.cs:line 615
   at VerifyTests.VerifyJsonWriter.Serialize(Object value) in /_/src/Verify/Serialization/VerifyJsonWriter.cs:line 289
   at InfoBuilder.Converter.Write(VerifyJsonWriter writer, InfoBuilder value) in /_/src/Verify/Serialization/InfoBuilder.cs:line 50
   at VerifyTests.WriteOnlyJsonConverter`1.Write(VerifyJsonWriter writer, Object value) in /_/src/Verify/Serialization/WriteOnlyJsonConverterT.cs:line 7
   at VerifyTests.WriteOnlyJsonConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer) in /_/src/Verify/Serialization/WriteOnlyJsonConverter.cs:line 12
   at JsonSerializerInternalWriter.SerializeConvertible(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty) in /_/src/Argon/Serialization/JsonSerializerInternalWriter.cs:line 538
   at JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty) in /_/src/Argon/Serialization/JsonSerializerInternalWriter.cs:line 116
   at JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type type) in /_/src/Argon/Serialization/JsonSerializerInternalWriter.cs:line 30
   at Argon.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type type) in /_/src/Argon/JsonSerializer.cs:line 649
   at Argon.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value) in /_/src/Argon/JsonSerializer.cs:line 615
   at JsonFormatter.AsJson(VerifySettings settings, Counter counter, Object value) in /_/src/Verify/Serialization/JsonFormatter.cs:line 7
   at VerifyTests.InnerVerifier.TryGetRootTarget(Object root, Nullable`1& target) in /_/src/Verify/Verifier/InnerVerifier_Inner.cs:line 140
   at VerifyTests.InnerVerifier.VerifyInner(Object root, Func`1 cleanup, IEnumerable`1 targets, Boolean doExpressionConversion) in /_/src/Verify/Verifier/InnerVerifier_Inner.cs:line 11
   at VerifyTests.InnerVerifier.Verify(Object target) in /_/src/Verify/Verifier/InnerVerifier_Object.cs:line 68
   at VerifyTests.InnerVerifier.Verify[T](Task`1 task) in /_/src/Verify/Verifier/InnerVerifier_Task.cs:line 11
   at VerifyTests.InnerVerifier.Verify[T](Task`1 task) in /_/src/Verify/Verifier/InnerVerifier_Task.cs:line 15
   at VerifyXunit.Verifier.<>c__DisplayClass9_0.<<Verify>b__0>d.MoveNext() in /_/src/Verify.Xunit/Verifier.cs:line 70
``` 

All details could be found:
- Dependabot PR: https://github.com/lkurzyniec/netcore-boilerplate/pull/396
- GH Action: https://github.com/lkurzyniec/netcore-boilerplate/actions/runs/11416042405?pr=396

If you need anything more, just let me know.

**Comment by SimonCropp** [comment]
fixed via PR
