### ISSUE TITLE
`The type initializer for 'DiffEngine.ProcessCleanup' threw an exception.` on running test

### ISSUE THREAD

**Issue by Xilconic** [VerifyTests/Verify#1350]
#### Describe the bug

When running a test that uses Verify, the following error is being reported:
```
System.TypeInitializationException: The type initializer for 'DiffEngine.ProcessCleanup' threw an exception.

System.TypeInitializationException
The type initializer for 'DiffEngine.ProcessCleanup' threw an exception.
   at DiffEngine.ProcessCleanup.TryGetProcessInfo(String command, ProcessCommand& process)
   at DiffEngine.DiffRunner.InnerLaunchAsync(TryResolveTool tryResolveTool, String tempFile, String targetFile, Encoding encoding) in C:\projects\diffengine\src\DiffEngine\DiffRunner.cs:line 146
   at VerifyEngine.RunDiffAutoCheck(FilePair file, Boolean autoVerify) in /_/src/Verify/Verifier/VerifyEngine.cs:line 255
   at VerifyEngine.ProcessNotEquals() in /_/src/Verify/Verifier/VerifyEngine.cs:line 211
   at VerifyEngine.ThrowIfRequired() in /_/src/Verify/Verifier/VerifyEngine.cs:line 133
   at VerifyTests.InnerVerifier.VerifyInner(Object root, Func`1 cleanup, IEnumerable`1 targets, Boolean doExpressionConversion) in /_/src/Verify/Verifier/InnerVerifier_Inner.cs:line 34
   at VerifyTests.InnerVerifier.Verify(Object target) in /_/src/Verify/Verifier/InnerVerifier_Object.cs:line 71
   at VerifyXunit.Verifier.<>c__DisplayClass9_0.<<Verify>b__0>d.MoveNext() in /_/src/Verify.Xunit/Verifier.cs:line 74
--- End of stack trace from previous location ---
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass47_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 259
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90

System.PlatformNotSupportedException
System.Management currently is only supported for Windows desktop applications.
   at System.Management.ManagementObjectSearcher..ctor(String queryString)
   at WindowsProcess.FindAll() in C:\projects\diffengine\src\DiffEngine\Process\WindowsProcess.cs:line 35
   at DiffEngine.ProcessCleanup.FindAll() in C:\projects\diffengine\src\DiffEngine\Process\ProcessCleanup.cs:line 98
   at DiffEngine.ProcessCleanup.Refresh() in C:\projects\diffengine\src\DiffEngine\Process\ProcessCleanup.cs:line 34
   at DiffEngine.ProcessCleanup..cctor() in C:\projects\diffengine\src\DiffEngine\Process\ProcessCleanup.cs:line 27

```
No diff window opens upon running the text.

Running the test does generate the expected `*.received.txt` and `*.verified.txt`, with the received file being empty and the verified file being empty.

From Rider, right clicking on the failed test to perform the "Accept Received" or "Compare Received/Verified" context menu command do not anything. The verified file remains unchanged.
Manually adjusting the verified file to have it match to received file does not make the error go away.

**Context:**

The code is running on an Windows machine (Microsoft Windows 11 Enterprise v10.0.22631 Build 22631), using Rider 2024.1.3 running dotnet version 8.0.300.

The project targets `dot6.0`.

Packages used:
- `xunit` v2.9.2
- `xunit.runner.visualstudio` v2.8.2
- `Verify.Xunit` 28.3.0
- `Microsoft.NET.Test.Sdk` 17.11.1

Rider has the `Verify Support` plugin installed, v2024.1.2.

dotnet tool `diffenginetray` v15.5.4 is installed and running in tray.

I found an earlier report similar to my observations: https://github.com/VerifyTests/Verify/issues/969

#### Minimal Repro
See attached zip file.
[TestProject1.zip](https://github.com/user-attachments/files/17774634/TestProject1.zip)

#### Submit a PR that fixes the bug
Unsure what's is causing the problem, therefore unsure how to fix the problem or suggest a PR.

**Comment by Xilconic** [comment]
As this is running on a corporate laptop, I wonder if a lack of admin rights could be the cause of this?

**Comment by Xilconic** [comment]
In the Minimal Repro, if I change the target from dotnet6.0 to dotnet8.0 the error goes away, and the diff-tool launches upon running the test.

**Comment by SimonCropp** [comment]
this is caused by me updating to the new System.Management. which for some reason thinks net6 is not windows and throws.

i have rolled back System.Management in 28.3.1 to get u unstuck. but given net6 is no longer supported, i suggest u update to a support version of dotnet

no point raising a bug with MS given net6 is unsupported

**Comment by Xilconic** [comment]
>i have rolled back System.Management in 28.3.1 to get u unstuck. but given net6 is no longer supported, i suggest u update to a support version of dotnet -SimonCropp

Thanks for the quick response!
I'm actually busy doing a migration to .NET8 for a project as we speak, and was experimenting with using Verify as a toolchain to lock in some current behavior for automated regression tests before upgrading all packages to the latest versions 👍
