### ISSUE TITLE
Issues when testing usign WSL2

### ISSUE THREAD

**Issue by koenbeuk** [VerifyTests/Verify#371]
When running `dotnet test` on fresh a WSL2 enabled Ubuntu distro (downloaded from the Windows store). I'm getting the following error outputted for failing Verify tests. Note that this Ubuntu distro does not have a desktop environment.

```
[xUnit.net 00:00:02.01]     EntityFrameworkCore.Projections.Generator.Tests.ProjectionExpressionGeneratorTests.BlockBodiedMethod_RaisesDiagnostics [FAIL]
[xUnit.net 00:00:02.19]     EntityFrameworkCore.Projections.Generator.Tests.ProjectionExpressionGeneratorTests.BlockBodiedMember_RaisesDiagnostics [FAIL]
  Failed EntityFrameworkCore.Projections.Generator.Tests.ProjectionExpressionGeneratorTests.BlockBodiedMethod_RaisesDiagnostics [100 ms]
  Error Message:
   System.Exception : Could not execute process. Command line: bash -c "cat /tmp/tmpBBMkzP.tmp | xsel -i --clipboard ".
Output:

Error: bash: xsel: command not found


  Stack Trace:
     at BashRunner.Run(String commandLine) in /_/src/TextCopy/BashRunner.cs:line 44
   at LinuxClipboard.SetTextAsync(String text, CancellationToken cancellation) in /_/src/TextCopy/LinuxClipboard_2.1.cs:line 19
   at ClipboardCapture.Append(String command) in /_/src/Verify/Clipboard/ClipboardCapture.cs:line 68
   at VerifyEngine.ProcessNotEquals(StringBuilder builder, FilePair item, String message) in /_/src/Verify/Verifier/VerifyEngine.cs:line 270
   at VerifyEngine.ProcessNotEquals(StringBuilder builder) in /_/src/Verify/Verifier/VerifyEngine.cs:line 216
   at VerifyEngine.ThrowIfRequired(String message) in /_/src/Verify/Verifier/VerifyEngine.cs:line 158
   at VerifyTests.InnerVerifier.VerifyInner(Object target, Func`1 cleanup, IEnumerable`1 targets) in /_/src/Verify/Verifier/InnerVerifier_Inner.cs:line 36
   at VerifyTests.InnerVerifier.Verify[T](T target) in /_/src/Verify/Verifier/InnerVerifier_Json.cs:line 79
   at VerifyXunit.Verifier.<>c__DisplayClass1_0.<<Verify>b__0>d.MoveNext() in /_/src/Verify.Xunit/Verifier.cs:line 29
--- End of stack trace from previous location ---
--- End of stack trace from previous location ---
```

This error within VerifyTests has 'swallowed' the output that I was hoping for, namely the difference between Received and Verified.

If I install xsel then another error pops up: 
```
[xUnit.net 00:00:00.92]     SyntaxLocationTests.ConsistentLocation [FAIL]
  Failed SyntaxLocationTests.ConsistentLocation [138 ms]
  Error Message:
   System.Exception : Could not execute process. Command line: bash -c "cat /tmp/tmpHpaZaW.tmp | xsel -i --clipboard ".
Output:

Error: xsel: Can't open display: (null)
: Inappropriate ioctl for device
...
```

**Comment by SimonCropp** [comment]
fixed by https://github.com/VerifyTests/Verify/commit/a9c34aeee4cd640bcdc0964ce697e6b0124b9c2f

**Comment by SimonCropp** [comment]
this is deployed now. can u try 11.18.1?

**Comment by koenbeuk** [comment]
I can confirm that its now working, thanks!
