### ISSUE TITLE
Relative Uri can not be serialized

### ISSUE THREAD

**Issue by DavidDeSloovere** [VerifyTests/Verify#375]
#### Describe the bug

A `Uri` of `Kind.Relative` can not be serialized. This used to work until v9. 

```
System.InvalidOperationException: This operation is not supported for a relative URI.
    at System.Uri.get_Query()
   at UriConverter.WriteJson(JsonWriter writer, Uri value, JsonSerializer serializer, IReadOnlyDictionary`2 context) in /_/src/Verify/Serialization/Converters/UriConverter.cs:line 17
   at VerifyTests.WriteOnlyJsonConverter`1.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer, IReadOnlyDictionary`2 context) in /_/src/Verify/Serialization/WriteOnlyJsonConverterT.cs:line 16
   at VerifyTests.WriteOnlyJsonConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer) in /_/src/Verify/Serialization/WriteOnlyJsonConverter.cs:line 24
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at JsonFormatter.AsJson(Object input, JsonSerializerSettings settings, List`1 appends, VerifySettings verifySettings) in /_/src/Verify/Serialization/JsonFormatter.cs:line 40
   at VerifyTests.InnerVerifier.TryGetTargetBuilder(Object target, StringBuilder& builder, String& extension) in /_/src/Verify/Verifier/InnerVerifier_Inner.cs:line 83
   at VerifyTests.InnerVerifier.VerifyInner(Object target, Func`1 cleanup, IEnumerable`1 targets) in /_/src/Verify/Verifier/InnerVerifier_Inner.cs:line 16
   at VerifyTests.InnerVerifier.Verify[T](T target) in /_/src/Verify/Verifier/InnerVerifier_Json.cs:line 107
   at VerifyMSTest.VerifyBase.<>c__DisplayClass5_0.<<Verify>b__0>d.MoveNext() in /_/src/Verify.MSTest/VerifyBase.cs:line 52
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)
```

#### Minimal Repro

Verify an instance of a class with a Uri, that is created with Kind.Relative.

#### Submit a PR that fixes the bug

#374

**Comment by SimonCropp** [comment]
can u try 11.18.4

**Comment by DavidDeSloovere** [comment]
Looks good. Thanks.
