### ISSUE TITLE
Verify.Xunit fails when .sln file is located in '/' directory

### ISSUE THREAD

**Issue by OlegKarasik** [VerifyTests/Verify#456]
All Verify.Xunit tests are failing when run on a solution located in '/' directory with the following exception:

```
System.ArgumentException : Empty name is not legal. (Parameter 'oldValue')
   at System.Text.StringBuilder.Replace(String oldValue, String newValue, Int32 startIndex, Int32 count)
   at System.Text.StringBuilder.Replace(String oldValue, String newValue)
   at ApplyScrubbers.<>c__DisplayClass5_0.<GetReplacements>b__2(StringBuilder builder) in /_/src/Verify/Serialization/Scrubbers/ApplyScrubbers.cs:line 83
   at ApplyScrubbers.Apply(String extension, StringBuilder target, VerifySettings settings) in /_/src/Verify/Serialization/Scrubbers/ApplyScrubbers.cs:line 106
   at VerifyEngine.GetResult(VerifySettings settings, FilePair filePair, Target target, Boolean previousTextHasFailed) in /_/src/Verify/Verifier/VerifyEngine.cs:line 38
   at VerifyEngine.HandleResults(List`1 targetList) in /_/src/Verify/Verifier/VerifyEngine.cs:line 60
   at InnerVerifier.VerifyInner(Object target, Func`1 cleanup, IEnumerable`1 targets) in /_/src/Verify/Verifier/InnerVerifier_Inner.cs:line 23
   at InnerVerifier.Verify[T](T target) in /_/src/Verify/Verifier/InnerVerifier_Json.cs:line 73
   at VerifyXunit.Verifier.<>c__DisplayClass1_0.<<Verify>b__0>d.MoveNext() in /_/src/Verify.Xunit/Verifier.cs:line 32
```

The issue is easily reproduced when running tests from a `Dockerfile`. Here is a small example of such `Dockerfile`:

```
# -- build --
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /

# copy *.sln
COPY /CSI.ASQ.Assessments.sln

# copy *.csproj
COPY /src/Core.Generators/*.csproj           /src/Core.Generators/
COPY /tests/Core.Generators.Tests/*.csproj   /tests/Core.Generators.Tests/

# dotnet restore
RUN dotnet restore

# copy source files
COPY /src/Core.Generators/src             /src/Core.Generators/src
COPY /tests/Core.Generators.Tests/src     /tests/Core.Generators.Tests/src

# dotnet build & test
RUN dotnet build   -c Release --no-restore
RUN dotnet test    -c Release --no-restore --no-build -r /results --logger "trx"
```

StackTrace lead me to the following line of code in [ApplyScrubbers.cs](https://github.com/VerifyTests/Verify/blob/4e39d7e83d56ef9267c425c59a99d77043c617a2/src/Verify/Serialization/Scrubbers/ApplyScrubbers.cs#L83):

``` csharp
builder.Replace(solutionDirectoryTrimmed, "{SolutionDirectory}"); 
```

The `solutionDirectoryTrimmed` variable is created a few line before by trimming back and forward slashes:

``` csharp
var solutionDirectoryTrimmed = solutionDirectory.TrimEnd('/', '\\')
```

So, in case when we have a `solutionDirectory` equal to '/' we trim the only character from it and receive an empty string. Which leads to the exception.

The workaround is quite simple - replace solution into some directory. In case of Dockerfile build it is very simple and not intrusive, so the issue is not something which can't be worked out.

**Comment by SimonCropp** [comment]
want to have a go at a PR for a fix?

**Comment by OlegKarasik** [comment]
@SimonCropp, Yes. I would try!

**Comment by SimonCropp** [comment]
@OlegKarasik any progress?

**Comment by SimonCropp** [comment]
can u try 16.3.2
