### ISSUE TITLE
Handling of paths with dots in VerifyDirectory

### ISSUE THREAD

**Issue by JanKrivanek** [VerifyTests/Verify#658]
## Description

` VerifyDirectory(directoryToVerify)` is not able to handle files without extensions (https://github.com/VerifyTests/Verify/blob/main/src/Verify/Verifier/InnerVerifier_Directory.cs#L69). If fixed, the extension-less files will cause issues if any of the parent folders will contain dot (https://github.com/VerifyTests/Verify/blob/main/src/Verify/Verifier/InnerVerifier_Directory.cs#L63 assumes the part after last dot to be an extension)

## Repro

**Case 1:**

```
[Fact]
public async Task VerifyDirectory_ExtensionLessFile()
{
    string dirName = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName().Replace(".", string.Empty));
    Directory.CreateDirectory(dirName);
    string fileName = Path.Combine(dirName, Path.GetRandomFileName().Replace(".", string.Empty));
    await File.WriteAllTextAsync(fileName, string.Empty);

    await VerifyDirectory(dirName);
}
```

throws

```
System.ArgumentOutOfRangeException
startIndex cannot be larger than length of string. (Parameter 'startIndex')
   at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex, Int32 length)
   at InnerVerifier.ToTargets(String path, Func`2 include, IEnumerable`1 enumerateFiles)+MoveNext() in /_/src/Verify/Verifier/InnerVerifier_Directory.cs:line 69
   at InnerVerifier.ToTargets(String path, Func`2 include, IEnumerable`1 enumerateFiles)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Extensions.ToList[T](IAsyncEnumerable`1 target) in /_/src/Verify/Extensions.cs:line 6
   at Extensions.ToList[T](IAsyncEnumerable`1 target) in /_/src/Verify/Extensions.cs:line 6
   at InnerVerifier.VerifyDirectory(String path, Func`2 include, String pattern, EnumerationOptions option) in /_/src/Verify/Verifier/InnerVerifier_Directory.cs:line 14
   at VerifyXunit.Verifier.<>c__DisplayClass6_0.<<Verify>b__0>d.MoveNext() in /_/src/Verify.Xunit/Verifier.cs:line 64
--- End of stack trace from previous location ---
   at XXX.VerifyDirectory_ExtensionLessFile()
```

**Case 2:**

```
[Fact]
public async Task VerifyDirectory_ExtensionLessFileInDirWithDot()
{
    string dirName = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
    Directory.CreateDirectory(dirName);
    string fileName = Path.Combine(dirName, Path.GetRandomFileName().Replace(".", string.Empty));
    await File.WriteAllTextAsync(fileName, string.Empty);

    await VerifyDirectory(dirName);
}
```

throws

```
System.ArgumentOutOfRangeException
startIndex cannot be larger than length of string. (Parameter 'startIndex')
   at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex, Int32 length)
   at InnerVerifier.ToTargets(String path, Func`2 include, IEnumerable`1 enumerateFiles)+MoveNext() in /_/src/Verify/Verifier/InnerVerifier_Directory.cs:line 66
   at InnerVerifier.ToTargets(String path, Func`2 include, IEnumerable`1 enumerateFiles)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Extensions.ToList[T](IAsyncEnumerable`1 target) in /_/src/Verify/Extensions.cs:line 6
   at Extensions.ToList[T](IAsyncEnumerable`1 target) in /_/src/Verify/Extensions.cs:line 6
   at InnerVerifier.VerifyDirectory(String path, Func`2 include, String pattern, EnumerationOptions option) in /_/src/Verify/Verifier/InnerVerifier_Directory.cs:line 14
   at VerifyXunit.Verifier.<>c__DisplayClass6_0.<<Verify>b__0>d.MoveNext() in /_/src/Verify.Xunit/Verifier.cs:line 64
--- End of stack trace from previous location ---
   at XXX.VerifyDirectory_ExtensionLessFileInDirWithDot()
```

## Fix suggestion

for Case 1:

`var extension = Path.GetExtension(file).Replace(".", stringEmpty);`

for Case 2:

`var name = Path.GetFileNameWithoutExtension(file);`

**Comment by SimonCropp** [comment]
can u submit a PR with a test and a fix

**Comment by JanKrivanek** [comment]
I submited PR - but feel free to close it and introduce different solution. It turns out that much more logic is dependent on presence of extensions. So for simplicity I workarounded this by appending artificial extension to received/verified files in case the original file has no extension.
